name: Build STM32 Bootloader/APP

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [APP0, Bootloader]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build project
      uses: xanderhendriks/action-build-stm32cubeide@v15.0
      with:
        project-path: ${{ matrix.project }}
        project-target: '${{ matrix.project }}/Debug'

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: firmware-${{ matrix.project }}
        path: | 
          ${{ matrix.project }}/Debug/*.elf
          ${{ matrix.project }}/Debug/*.bin
